services:
  redis-node-1:
    build:
      context: .
      dockerfile: Containerfile
    image: redis-cluster-node:latest
    container_name: redis-node-1
    hostname: redis-node-1
    ports:
      - "2221:22"
    networks:
      redis-net:
        ipv4_address: 10.10.0.11
  redis-node-2:
    image: redis-cluster-node:latest
    container_name: redis-node-2
    hostname: redis-node-2
    ports:
      - "2222:22"
    networks:
      redis-net:
        ipv4_address: 10.10.0.12
    depends_on:
      - redis-node-1
  redis-node-3:
    image: redis-cluster-node:latest
    container_name: redis-node-3
    hostname: redis-node-3
    ports:
      - "2223:22"
    networks:
      redis-net:
        ipv4_address: 10.10.0.13
    depends_on:
      - redis-node-1
  redis-node-4:
    image: redis-cluster-node:latest
    container_name: redis-node-4
    hostname: redis-node-4
    ports:
      - "2224:22"
    networks:
      redis-net:
        ipv4_address: 10.10.0.14
    depends_on:
      - redis-node-1
  redis-node-5:
    image: redis-cluster-node:latest
    container_name: redis-node-5
    hostname: redis-node-5
    ports:
      - "2225:22"
    networks:
      redis-net:
        ipv4_address: 10.10.0.15
    depends_on:
      - redis-node-1
  redis-node-6:
    image: redis-cluster-node:latest
    container_name: redis-node-6
    hostname: redis-node-6
    ports:
      - "2226:22"
    networks:
      redis-net:
        ipv4_address: 10.10.0.16
    depends_on:
      - redis-node-1
networks:
  redis-net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "true"
    ipam:
      driver: default
      config:
        - subnet: 10.10.0.0/24
          gateway: 10.10.0.1